import { task } from "hardhat/config";
import type { TaskArguments } from "hardhat/types";
import { promises as fs } from "node:fs";
import path from "node:path";

type DeploymentJson = {
  address: string;
  abi: unknown;
};

function assertDeploymentShape(name: string, value: any): asserts value is DeploymentJson {
  if (!value || typeof value !== "object") throw new Error(`${name} deployment JSON is missing`);
  if (typeof value.address !== "string") throw new Error(`${name} deployment JSON has no address`);
  if (!("abi" in value)) throw new Error(`${name} deployment JSON has no abi`);
}

async function readDeployment(rootDir: string, network: string, name: string): Promise<DeploymentJson> {
  const filePath = path.join(rootDir, "deployments", network, `${name}.json`);
  const raw = await fs.readFile(filePath, "utf8");
  const parsed = JSON.parse(raw);
  assertDeploymentShape(name, parsed);
  return parsed;
}

function stringifyAbi(abi: unknown) {
  return JSON.stringify(abi, null, 2);
}

task("task:sync-frontend", "Writes contract addresses + ABI to home/src/config/contracts.ts (from deployments/sepolia)")
  .addOptionalParam("networkName", "Deployment folder name", "sepolia")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const repoRoot = hre.config.paths.root;
    const networkName = String(taskArguments.networkName || "sepolia");

    const token = await readDeployment(repoRoot, networkName, "fUSDT");
    const factory = await readDeployment(repoRoot, networkName, "ZaLiftFactory");
    const campaign = await readDeployment(repoRoot, networkName, "ZaLiftCampaign");

    const outPath = path.join(repoRoot, "home", "src", "config", "contracts.ts");

    const contents = `// Auto-generated by \`npx hardhat task:sync-frontend --networkName ${networkName}\`
// Source: deployments/${networkName}/*.json

export const SEPOLIA_CHAIN_ID = 11155111;

export const FUSDT_ADDRESS = "${token.address}";
export const FUSDT_ABI = ${stringifyAbi(token.abi)} as const;

export const ZALIFT_FACTORY_ADDRESS = "${factory.address}";
export const ZALIFT_FACTORY_ABI = ${stringifyAbi(factory.abi)} as const;

// ZaLiftCampaign is deployed once as an ABI template; factory-created campaigns share the same ABI.
export const ZALIFT_CAMPAIGN_ABI = ${stringifyAbi(campaign.abi)} as const;
`;

    await fs.writeFile(outPath, contents, "utf8");
    console.log(`Wrote ${outPath}`);
  });

